# Site settings
title: Kubernutty.io | All things Docker and Kubernetes
description: "We are Docker and Kubernetes enthusiast who uses this set of technologies to deploy everything!"
url: "http://www.kubernutty.io"
author:
  name: "Kubernutty.io"
  email: "support@kubernutty.com"
  url: "https://www.kubernutty.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
