# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            ""
tagline:          'This is a place for us to blog about Kubernetes and talk about our experience with it'
description:      'This is a place for us to blog about Kubernetes and talk about our experience with it'
url:              https://www.kubernutty.io
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Garland'
  url:            https://www.kubernutty.io

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            false
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://kubernutty.github.io/blog

google_analytics: UA-97032087-1
